apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: 'https://github.com/#GITHUB_ORG_NAME#/#GITHUB_REPO_NAME#?rev={{revision}}' # >> changeme
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    appstudio.openshift.io/request: "configure-pac"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[#EVENT_TYPE#]' # >> changeme
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  labels:
    appstudio.openshift.io/application: #APPLICATION_NAME#  # >> changeme
    appstudio.openshift.io/component: #COMPONENT_NAME# # >> changeme
    pipelinesascode.tekton.dev/pipeline: #REMOTE_PIPELINE# # >> changeme
    pipelines.appstudio.openshift.io/type: build
    rhtap.snowdrop.dev/build: "test-#BUILD_ID#" # >> changeme
  name: #PAC_NAME# # >> changeme
  namespace: #TENANT_NAMESPACE# # >> changeme
spec:
  params:
    - name: dockerfile
      value: https://raw.githubusercontent.com/devfile-samples/devfile-sample-code-with-quarkus/main/src/main/docker/Dockerfile.jvm.staged
    - name: git-url
      value: '{{repo_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      # This param will also be used by the pipeline to set the Buildpacks AppImage param
      value: #REGISTRY_URL#:build-{{revision}} # >> changeme
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
    # Buildpacks parameters
    - name: sourceSubPath
      value: "#SOURCE_SUB_PATH#" # >> changeme
    - name: cnbLogLevel
      value: "#CNB_LOG_LEVEL#" # >> changeme
    - name: cnbBuilderImage
      value: "#CNB_BUILDER_IMAGE#" # >> changeme
    - name: cnbBuildImage
      value: "#CNB_BUILD_IMAGE#" # >> changeme
    - name: cnbRunImage
      value: "#CNB_RUN_IMAGE#" # >> changeme
    - name: ENV_VARS
      value: "[#CNB_ENV_VARS#]" # >> changeme
  pipelineRef:
    name: pipeline-rhtap
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
